Multi az
redpanda-data/deployment-automation pull request #133
Opened 2023-02-02 20:09 UTC by tmgstevens

Draft PR for mutli AZ terraform. There's a merge error in there for some reason, which I'll go back at fix, but wanted to get this out there.

2023-03-03 18:11 UTC, vuldin requested changes
I've tested on AWS and GCP, and found an issue with the GCP changes (comments below). I'll test on Azure soon.

2023-03-03 18:11 UTC, vuldin commented on azure/vars.tf
> +  default     = []
Changing this variable name requires the following line to be updated: https://github.com/redpanda-data/deployment-automation/blob/main/gcp/provider.tf#L4

The immediate issue I see is that the `zone` parameter takes a single value, but `var.availability_zone` is a tuple. It looks like this is just used as the default zone, and any zone added to sub-resources will take precedence.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference

2023-03-07 07:08 UTC, tmgstevens commented on azure/vars.tf
> +  default     = []
Fixed the GCP issue.

2023-03-07 20:10 UTC, gene-redpanda commented
@tmgstevens https://github.com/redpanda-data/deployment-automation/pull/151 I've updated this with the latest stuff from main and resolved the merge commits. LMK when you get a sec to give it a once over.

2023-04-11 14:32 UTC, tmgstevens commented
Fixed by #165

2023-04-11 14:32 UTC, closed without merging